{{- range $serviceName, $service := .Values.services }}
{{- if ne $service.enabled false }}
{{- $labels := dict "name" $serviceName "root" $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "online-boutique.selectorLabels" $labels | nindent 4 }}
    {{- include "online-boutique.commonLabels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: {{ $service.protocol | default "http" }}
      port: {{ $service.port }}
      targetPort: {{ $service.port }}
      protocol: TCP
      appProtocol: {{ $service.protocol | default "http" }}
  selector:
    {{- include "online-boutique.selectorLabels" $labels | nindent 4 }}
{{- end }}
{{- end }}