{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-sa" .Chart.Name) }}
  labels:
    {{- include "online-boutique.commonLabels" $ | nindent 4 }}
{{- end }}